import BodyMeshProviderCore
import Fabric
import Foundation
import Metal
import Satin
import simd

public final class BodyMeshIntrinsicCameraNode: ObjectNode<PerspectiveCamera>
{
    public override class var name: String { "Body Mesh Intrinsic Camera" }
    public override class var nodeType: Node.NodeType { .Object(objectType: .Camera) }
    public override class var nodeExecutionMode: Node.ExecutionMode { .Consumer }
    public override class var nodeTimeMode: Node.TimeMode { .None }
    public override class var nodeDescription: String
    {
        "Provides the intrinsic source camera for body meshes generated by the generator app."
    }

    public static let defaultSourceSize = SIMD2<Float>(1920, 1080)
    public static let defaultOrientation = SIMD4<Float>(0, 0, 0, 1)

    private static let nearPlane: Float = 0.01
    private static let farPlane: Float = 500

    private lazy var camera = PerspectiveCamera(
        context: context,
        position: .zero,
        near: Self.nearPlane,
        far: Self.farPlane
    )
    private var viewportAspectRatio: Float = 1

    public override class func registerPorts(
        context: Context
    ) -> [(name: String, port: Fabric.Port)]
    {
        let objectPorts = super.registerPorts(context: context).filter
        {
            ["inputPosition", "inputScale", "inputOrientation"].contains($0.name) == false
        }

        return [
            (
                "inputSourceSize",
                ParameterPort(
                    parameter: Float2Parameter(
                        "Source Size",
                        defaultSourceSize,
                        .inputfield,
                        "Encoded source width and height from Body Mesh Provider"
                    )
                )
            ),
            (
                "inputOrientation",
                ParameterPort(
                    parameter: Float4Parameter(
                        "Orientation",
                        defaultOrientation,
                        .inputfield,
                        "Camera orientation as a quaternion; identity looks along -Z"
                    )
                )
            ),
            (
                "inputScale",
                ParameterPort(
                    parameter: Float3Parameter(
                        "Scale",
                        .one,
                        .inputfield,
                        "Scales the camera view"
                    )
                )
            ),
            (
                "inputPosition",
                ParameterPort(
                    parameter: Float3Parameter(
                        "Position",
                        .zero,
                        .inputfield,
                        "Camera position; the generated body mesh is calibrated at the origin"
                    )
                )
            ),
        ] + objectPorts
    }

    public var inputSourceSize: ParameterPort<SIMD2<Float>>
    {
        port(named: "inputSourceSize")
    }

    public override var object: PerspectiveCamera? { camera }

    public override func startExecution(renderer: GraphRenderer) throws
    {
        try super.startExecution(renderer: renderer)
        camera.position = inputPosition.value ?? .zero
        camera.scale = inputScale.value ?? .one
        camera.orientation = safeOrientation(
            inputOrientation.value ?? Self.defaultOrientation
        )
        updateProjection()
    }

    public override func evaluate(object: Object?, atTime: TimeInterval) -> Bool
    {
        let shouldUpdate = super.evaluate(object: object, atTime: atTime)

        if inputOrientation.valueDidChange
        {
            camera.orientation = safeOrientation(
                inputOrientation.value ?? Self.defaultOrientation
            )
        }
        if inputSourceSize.valueDidChange
        {
            updateProjection()
        }

        return shouldUpdate || inputSourceSize.valueDidChange
    }

    public override func execute(
        renderer: GraphRenderer,
        executionInfo: GraphExecutionInfo,
        renderPassDescriptor: MTLRenderPassDescriptor,
        commandBuffer: MTLCommandBuffer
    ) throws
    {
        _ = evaluate(object: camera, atTime: executionInfo.timing.time)
    }

    public override func resize(
        size: (width: Float, height: Float),
        scaleFactor: Float
    )
    {
        guard size.width.isFinite,
              size.height.isFinite,
              size.width > 0,
              size.height > 0
        else { return }

        viewportAspectRatio = size.width / size.height
        updateProjection()
    }

    private func updateProjection()
    {
        guard let sourceSize = inputSourceSize.value,
              let projection = try? BodyMeshIntrinsicCameraProjection(
                  sourceSize: sourceSize
              ),
              let fieldOfView = try? projection.verticalFieldOfView(
                  viewportAspectRatio: viewportAspectRatio
              )
        else { return }

        camera.aspect = viewportAspectRatio
        camera.fov = fieldOfView
    }

    private func safeOrientation(_ vector: SIMD4<Float>) -> simd_quatf
    {
        let lengthSquared = simd_length_squared(vector)
        guard lengthSquared.isFinite, lengthSquared > 0 else
        {
            return simd_quatf(vector: Self.defaultOrientation)
        }
        return simd_quatf(vector: vector / sqrt(lengthSquared))
    }
}
